[general]
font-sans = "JetBrainsMono Nerd Font Propo"
font-mono = "JetBrainsMono Nerd Font Propo"

[bar]
padding = 0.10000000149011612
button-variant = "basic"
button-bg-opacity = 0
button-icon-size = 0.5
button-label-size = 0.800000011920929
button-label-padding = 0.4000000059604645

[[bar.layout]]
monitor = "*"
show = true
left = [
    "dashboard",
    "separator",
    "hyprland-workspaces",
    "cava",
]
center = ["clock"]
right = [
    "keyboard-input",
    "separator",
    "custom-webcam",
    "bluetooth",
    "network",
    "microphone",
    "volume",
    "notifications",
]

[styling]
rounding = "none"

[styling.palette]
bg = "#16161e"
surface = "#1a1b26"
elevated = "#202230"
fg = "#c0caf5"
fg-muted = "#a9b1d6"
primary = "#7aa2f7"
red = "#f7768e"
yellow = "#e0af68"
green = "#9ece6a"
blue = "#7dcfff"

[modules.bluetooth]
icon-color = "fg-default"
icon-bg-color = "auto"
label-show = false

[modules.cava]
color = "fg-default"
left-click = "dropdown:media"

[modules.clock]
format = "%H:%M:%S"
icon-show = false
label-color = "fg-default"
right-click = ""
dropdown-show-seconds = true

[modules.dashboard]
icon-color = "fg-default"
dropdown-logout-command = 'hyprctl dispatch "hl.dsp.exit()"'

[modules.hyprland-workspaces]
min-workspace-count = 5
monitor-specific = false
label-size = 0.75
active-color = "fg-default"

[modules.keyboard-input]
icon-color = "fg-default"
label-color = "fg-default"
left-click = "hyprctl switchxkblayout all next"

[modules.keyboard-input.layout-alias-map]
Italian = "IT"
"English (US)" = "US"

[modules.media]
icon-type = "spinning-disc"
player-priority = [
    "*spotify*",
    "*mpv*",
    "*firefox*",
]
format = "{{ title }}"
label-max-length = 20

[modules.microphone]
icon-color = "fg-default"
label-show = false

[modules.network]
icon-color = "fg-default"
label-show = false

[modules.notification]
icon-color = "fg-default"
label-show = false
popup-position = "bottom-right"

[modules.separator]
length = 0.699999988079071

[modules.volume]
icon-color = "fg-default"
label-show = false
label-color = "fg-default"

[[modules.custom]]
id = "webcam"
command = "~/.config/scripts/waybar-webcam-status.sh"
mode = "poll"
interval-ms = 2000
restart-policy = "never"
restart-interval-ms = 1000
format = "{{ output }}"
hide-if-empty = true
icon-name = "ld-camera-symbolic"
icon-show = true
icon-color = "red"
icon-bg-color = "auto"
label-show = false
label-color = "auto"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = "~/.config/scripts/toggle-webcam.sh"
right-click = ""
middle-click = ""
scroll-up = ""
scroll-down = ""

[modules.custom.icon-map]
active = "ld-camera-symbolic"
disabled = "ld-eye-off-symbolic"

[osd]
duration = 1500
margin = 100.0

[wallpaper]
engine-enabled = false
