[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""

FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

Background="__WALLPAPER__"
BackgroundPlaceholder=""
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#c0caf5"
DateTextColor="#c0caf5"
TimeTextColor="#7dcfff"

FormBackgroundColor="#1a1b26"
BackgroundColor="#1a1b26"
DimBackgroundColor="#1a1b26"

LoginFieldBackgroundColor="#1a1b26"
PasswordFieldBackgroundColor="#1a1b26"
LoginFieldTextColor="#c0caf5"
PasswordFieldTextColor="#c0caf5"
UserIconColor="#c0caf5"
PasswordIconColor="#c0caf5"

PlaceholderTextColor="#7dcfff"
WarningColor="#f7768e"

LoginButtonTextColor="#1a1b26"
LoginButtonBackgroundColor="#7dcfff"
SystemButtonsIconsColor="#7dcfff"
SessionButtonTextColor="#7dcfff"
VirtualKeyboardButtonTextColor="#7dcfff"

DropdownTextColor="#c0caf5"
DropdownSelectedBackgroundColor="#7dcfff"
DropdownBackgroundColor="#1a1b26"

HighlightTextColor="#1a1b26"
HighlightBackgroundColor="#7dcfff"
HighlightBorderColor="#7dcfff"

HoverUserIconColor="#7dcfff"
HoverPasswordIconColor="#7dcfff"
HoverSystemButtonsIconsColor="#c0caf5"
HoverSessionButtonTextColor="#c0caf5"
HoverVirtualKeyboardButtonTextColor="#c0caf5"

PartialBlur="true"
FullBlur="false"
BlurMax="64"
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
