[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""

FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

Background="__WALLPAPER__"
BackgroundPlaceholder=""
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#ffffff"
DateTextColor="#ffffff"
TimeTextColor="#78a9ff"

FormBackgroundColor="#161616"
BackgroundColor="#161616"
DimBackgroundColor="#161616"

LoginFieldBackgroundColor="#262626"
PasswordFieldBackgroundColor="#262626"
LoginFieldTextColor="#ffffff"
PasswordFieldTextColor="#ffffff"
UserIconColor="#ffffff"
PasswordIconColor="#ffffff"

PlaceholderTextColor="#78a9ff"
WarningColor="#ee5396"

LoginButtonTextColor="#161616"
LoginButtonBackgroundColor="#78a9ff"
SystemButtonsIconsColor="#78a9ff"
SessionButtonTextColor="#78a9ff"
VirtualKeyboardButtonTextColor="#78a9ff"

DropdownTextColor="#ffffff"
DropdownSelectedBackgroundColor="#78a9ff"
DropdownBackgroundColor="#161616"

HighlightTextColor="#161616"
HighlightBackgroundColor="#78a9ff"
HighlightBorderColor="#78a9ff"

HoverUserIconColor="#33b1ff"
HoverPasswordIconColor="#33b1ff"
HoverSystemButtonsIconsColor="#ffffff"
HoverSessionButtonTextColor="#ffffff"
HoverVirtualKeyboardButtonTextColor="#ffffff"

PartialBlur="true"
FullBlur="false"
BlurMax="64"
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
