[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""

FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

Background="__WALLPAPER__"
BackgroundPlaceholder=""
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#C5C9C7"
DateTextColor="#C5C9C7"
TimeTextColor="#8ba4b0"

FormBackgroundColor="#14171d"
BackgroundColor="#14171d"
DimBackgroundColor="#14171d"

LoginFieldBackgroundColor="#14171d"
PasswordFieldBackgroundColor="#14171d"
LoginFieldTextColor="#C5C9C7"
PasswordFieldTextColor="#C5C9C7"
UserIconColor="#C5C9C7"
PasswordIconColor="#C5C9C7"

PlaceholderTextColor="#8ba4b0"
WarningColor="#c4746e"

LoginButtonTextColor="#14171d"
LoginButtonBackgroundColor="#8ba4b0"
SystemButtonsIconsColor="#8ba4b0"
SessionButtonTextColor="#8ba4b0"
VirtualKeyboardButtonTextColor="#8ba4b0"

DropdownTextColor="#C5C9C7"
DropdownSelectedBackgroundColor="#8ba4b0"
DropdownBackgroundColor="#14171d"

HighlightTextColor="#14171d"
HighlightBackgroundColor="#8ba4b0"
HighlightBorderColor="#8ba4b0"

HoverUserIconColor="#8ba4b0"
HoverPasswordIconColor="#8ba4b0"
HoverSystemButtonsIconsColor="#C5C9C7"
HoverSessionButtonTextColor="#C5C9C7"
HoverVirtualKeyboardButtonTextColor="#C5C9C7"

PartialBlur="true"
FullBlur="false"
BlurMax="64"
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
