[General]
ScreenWidth="2560"
ScreenHeight="1440"
ScreenPadding=""

FontSize="13"
KeyboardSize="0.4"
RoundCorners="20"
HourFormat="HH:mm"
DateFormat="dddd d MMMM"
HeaderText=""

Background="__WALLPAPER__"
BackgroundPlaceholder=""
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.0"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

HeaderTextColor="#cdd6f4"
DateTextColor="#cdd6f4"
TimeTextColor="#f5c2e7"

FormBackgroundColor="#1e1e2e"
BackgroundColor="#1e1e2e"
DimBackgroundColor="#1e1e2e"

LoginFieldBackgroundColor="#313244"
PasswordFieldBackgroundColor="#313244"
LoginFieldTextColor="#cdd6f4"
PasswordFieldTextColor="#cdd6f4"
UserIconColor="#cdd6f4"
PasswordIconColor="#cdd6f4"

PlaceholderTextColor="#bac2de"
WarningColor="#f38ba8"

LoginButtonTextColor="#1e1e2e"
LoginButtonBackgroundColor="#f5c2e7"
SystemButtonsIconsColor="#f5c2e7"
SessionButtonTextColor="#f5c2e7"
VirtualKeyboardButtonTextColor="#f5c2e7"

DropdownTextColor="#cdd6f4"
DropdownSelectedBackgroundColor="#f5c2e7"
DropdownBackgroundColor="#1e1e2e"

HighlightTextColor="#1e1e2e"
HighlightBackgroundColor="#f5c2e7"
HighlightBorderColor="#f5c2e7"

HoverUserIconColor="#f5c2e7"
HoverPasswordIconColor="#f5c2e7"
HoverSystemButtonsIconsColor="#cdd6f4"
HoverSessionButtonTextColor="#cdd6f4"
HoverVirtualKeyboardButtonTextColor="#cdd6f4"

PartialBlur="true"
FullBlur="false"
BlurMax="64"
Blur=""
HaveFormBackground="false"
FormPosition="left"

VirtualKeyboardPosition="center"

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"
ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
